const Bestiariodata = [
  {
    id: 1,
    nombre: 'Azathoth',
    relato: 'Relato: Hongos de Yuggoth',
    descripcion: 'Azathoth es una deidad cósmica primordial en la mitología de Lovecraft, considerada el "Caos Nuclear" del universo. Es un ser ciego, idiota y dormido, cuyo constante ruido y caos son la base misma de la creación. Aunque su existencia es ajena a cualquier noción humana de conciencia o propósito, su influencia es fundamental para el funcionamiento del cosmos.',
    imagen: '../assets/img/azathoth.webp',
  },
  {
    id: 2,
    nombre: 'Bestias Lunares',
    relato: 'Relato: En busca de la Ciudad del Sol Poniente',
    descripcion: 'Las Bestias Lunares son criaturas misteriosas y monstruosas que habitan en la Luna, según la mitología de Lovecraft. Se describen como seres de gran tamaño y apariencia alienígena, con formas que varían, pero generalmente asociadas con el terror y el caos cósmico.',
    imagen: '../assets/img/MoonBeasts_29.webp',
  },
  {
    id: 3,
    nombre: 'Chaugnar Faugn',
    relato: 'Relato: El horror en el museo',
    descripcion: 'Chaugnar Faugn es una deidad monstruosa de la mitología de Lovecraft, descrita como una gigantesca criatura con cuerpo de elefante y tentáculos. Es conocida por su naturaleza cruel y su poder destructivo, adorada por cultos oscuros.',
    imagen: '../assets/img/chaugnarfaugn.webp',
  },
  {
    id: 4,
    nombre: 'Cthulhu',
    relato: 'Relato: La llamada de Cthulhu',
    descripcion: 'Se describe como una gigantesca criatura con cuerpo de pulpo, alas de dragón y un rostro cubierto de tentáculos. Cthulhu reside en la sumergida ciudad de Rlyeh, en el océano Pacífico, donde yace en un sueño profundo, esperando el momento en que despierte para traer caos y destrucción a la humanidad. Su influencia es tal que su presencia puede inducir la locura a aquellos que tienen contacto con él o sus cultos. Su nombre es sinónimo del horror cósmico y la insignificancia humana frente a las fuerzas del universo.',
    imagen: '../assets/img/Lovecraft-cthulhu.webp',
  },
  {
    id: 5,
    nombre: 'Dagón',
    relato: 'Relato: Dagón',
    descripcion: 'Dagón es una deidad marina primitiva en la mitología lovecraftiana, asociada con el culto de los profundos. Es una criatura gigantesca, con forma de pez humanoide, venerada por los habitantes de las ciudades sumergidas y conocida por su conexión con las fuerzas del océano y el horror cósmico',
    imagen: '../assets/img/dagon.webp',
  },
  {
    id: 6,
    nombre: 'Engendros de Cthulhu',
    relato: 'Relato: En las montañas de la locura',
    descripcion: 'Los Engendros de Cthulhu son criaturas monstruosas que sirven a Cthulhu. Se describen con características similares a su maestro: cuerpos gelatinosos, tentáculos, alas y rostros amorfos. Habitan en las profundidades del océano y emergen para cumplir con la voluntad de su deidad primordial, sembrando terror y caos.',
    imagen: '../assets/img/engendro de cuthulu.jpeg',
  },
  {
    id: 7,
    nombre: 'Gran Raza de Yith',
    relato: 'Relato: La sombra sobre Innsmouth',
    descripcion: 'La Gran Raza de Yith es una antigua y avanzada civilización extraterrestre en la mitología de Lovecraft. Son seres con cuerpos similares a medusas, que poseen una increíble inteligencia y pueden transferir sus mentes a otros seres, como humanos, para tomar control de sus cuerpos y explorar diferentes épocas y lugares.',
    imagen: '../assets/img/granraza.webp',
  },
  {
    id: 8,
    nombre: 'Grandes Antiguos',
    relato: 'Relato: En las montañas de la locura',
    descripcion: 'Aparentemente, su anatomía se asemeja por igual a las plantas y los animales. Se reproducen por esporas o bipartición y pueden descomponer materia para nutrirse, aunque prefieren comer carne. Son anfibios y poseen cinco lóbulos cerebrales.',
    imagen: '../assets/img/grandes antiguos.webp',
  },
  {
    id: 9,
    nombre: 'Gugos',
    relato: 'Relato: En busca de la Ciudad del Sol Poniente',
    descripcion: 'Los Gugos son criaturas gigantes y primitivas de la mitología lovecraftiana, descritas como humanoides con cuerpos musculosos, con ojos brillantes y garras afiladas. Se encuentran en las profundas cavernas subterráneas y son conocidos por su brutalidad y su naturaleza agresiva.',
    imagen: '../assets/img/Gugos.webp',
  },
  {
  id: 10,
  nombre: 'Gules',
  relato: 'Relato: El modelo de Pickman',
  descripcion: 'Los Gules son criaturas espectrales y malignas que aparecen en algunas historias de la mitología de Lovecraft. Se describen como seres de naturaleza vampírica o carroñera, que se alimentan de la carne y la sangre de los vivos, acechando en la oscuridad y sembrando el terror.',
  imagen: '../assets/img/Ghouls.webp',
},
{
  id: 11,
  nombre: 'Hastur',
  relato: 'Relato: El que susurra en la obscuridad',
  descripcion: 'Hastur es una entidad cósmica asociada con la locura, el caos y el misterio, conocida como el Rey de Amarillo.',
  imagen: '../assets/img/hastur.webp',
},
{
  id: 12,
  nombre: 'Mi-go',
  relato: 'Relato: El que susurra en la obscuridad',
  descripcion: 'Los Mi-Go son una raza alienígena insectoide de Yuggoth, conocida por su tecnología avanzada y su indiferencia hacia los humanos, a quienes usan para experimentos científicos, como la extracción de cerebros para preservarlos en frascos.',
  imagen: '../assets/img/migo.webp',
},
{
  id: 13,
  nombre: 'Nocturnos',
  relato: 'Relato: Angeles descarnados de la noche',
  descripcion: 'Los Nocturnos son criaturas sombrías y misteriosas en la mitología de Lovecraft, asociadas con la oscuridad y el silencio. Se dice que se alimentan de la energía vital de los seres humanos y suelen habitar en lugares aislados y desolados, acechando en la penumbra.',
  imagen: '../assets/img/nocturnos.webp',
},
{
  id: 14,
  nombre: 'Nyarlathotep',
  relato: 'Relato: Hongos de Yuggoth',
  descripcion: 'Nyarlathotep es una entidad cósmica en la mitología de Lovecraft, conocida como el Caos Reptante. A diferencia de otras deidades cósmicas, tiene una forma mutable y puede tomar diversas apariencias, incluso humanas. Es un mensajero de los dioses exteriores, y a menudo se presenta como una figura que siembra el caos y la locura entre los mortales.',
  imagen: '../assets/img/nyarlathothep.webp',
},
{
  id: 15,
  nombre: 'Pingüinos de Leng',
  relato: 'Relato: En las montañas de la locura',
  descripcion: 'Los Pingüinos de Leng son criaturas gigantescas y albinas que habitan en las regiones heladas del continente antártico, especialmente en las cavernas subterráneas cercanas a las ruinas de la ciudad de los Antiguos. Son ciegos debido a la oscuridad perpetua de su entorno y suelen ser un elemento perturbador en las historias vinculadas a esas regiones misteriosas.',
  imagen: '../assets/img/pinguinosdeleng.webp',
},
{
  id: 16,
  nombre: 'Pólipos',
  relato: 'Relato: La sombra más allá del tiempo',
  descripcion: 'Los Pólipos son criaturas alienígenas en la mitología de Lovecraft, descritas como seres de aspecto tentacular y viscoso. Se caracterizan por su naturaleza grotesca y su capacidad para sobrevivir en ambientes extremos, como las profundidades del océano o lugares alienígenas. Son conocidos por su hostilidad y por su conexión con entidades cósmicas y cultos oscuros.',
  imagen: '../assets/img/polipos.webp',
},
{
  id: 17,
  nombre: 'Profundos',
  relato: 'Relato: La sombra sobre Innsmouth',
  descripcion: 'Los Profundos son seres acuáticos humanoides, adoradores de deidades como Dagón y Cthulhu, que habitan en las profundidades del océano. Se caracterizan por su apariencia grotesca, con piel escamosa, ojos grandes y capacidad para respirar bajo el agua, y son conocidos por su culto oscuro y su hostilidad hacia los humanos.',
  imagen: '../assets/img/profundos.webp',
},
{
  id: 18,
  nombre: 'Rhan-Tegoth',
  relato: 'Relato: El horror en el museo',
  descripcion: 'Rhan-Tegoth es una deidad cósmica en la mitología de Lovecraft, representada como una criatura gigantesca con aspecto de insecto, que habita en los remotos rincones de la Tierra. Es conocida por su naturaleza destructiva y su asociación con el caos y la oscuridad.',
  imagen: '../assets/img/Rhan.webp',
},
{
  id: 19,
  nombre: 'Shoggoths',
  relato: 'Relato: En las montañas de la locura',
  descripcion: 'Los Shoggoths son seres amorfos y protoplásmicos creados por los Antiguos. Están compuestos por una masa gelatinosa negra y viscosa, capaz de formar ojos, extremidades y bocas según necesiten. Originalmente esclavos constructores, se rebelaron contra sus creadores. Son extremadamente fuertes, adaptables y pueden provocar locura en quienes los observan.',
  imagen: '../assets/img/Shoggoth.webp',
},
{
  id: 20,
  nombre: 'Shub-Niggurath',
  relato: 'Relato: El que susurra en la obscuridad',
  descripcion: 'Shub-Niggurath es una deidad cósmica de la fertilidad, frecuentemente representada como una cabra negra con mil retoños. Es una entidad alienígena y corruptora, asociada con la decadencia y el horror primigenio.',
  imagen: '../assets/img/Shub-Niggurath.webp',
},
{
  id: 21,
  nombre: 'Tsathoggua',
  relato: 'Relato: El que susurra en la obscuridad',
  descripcion: 'Tsathoggua es una deidad antigua, descrita como una criatura rechoncha, perezosa y con aspecto de sapo o murciélago.',
  imagen: '../assets/img/Tsathoggua.webp',
},
{
  id: 22,
  nombre: 'Yog-Sothoth',
  relato: 'Relato: El horror en Dunwich',
  descripcion: 'Yog-Sothoth es una deidad cósmica omnisciente y trascendental en la mitología de Lovecraft. Se describe como una entidad compuesta por esferas interconectadas, y se considera la clave del universo, estando presente en todos los tiempos y espacios simultáneamente.',
  imagen: '../assets/img/yog-sothoth.webp',
},
];

export default Bestiariodata;
